#!/usr/bin/env python3

import sys


def info():
    print("info")

def upload():
    print("upload")

def start(file_name):
    print("start" + file_name)

def finish(file_name):
    print("finish" + file_name)

def grade(file_name):
    print("grade" + file_name)

def hint(file_name):
    print("hint" + file_name)


if len(sys.argv) > 4: 
    print("Usage: JEDU <arg1> <arg2> <arg3>")
    sys.exit(1)

command_arg = sys.argv[1]

if command_arg == "info":
    info()
elif command_arg == "upload" and len(sys.argv) > 2:
    upload()
elif command_arg == "lab" and len(sys.argv) > 3:
    option_arg = sys.argv[2]
    file_arg = sys.argv[3]
    if option_arg == "start":
        start(file_arg)
    elif option_arg == "finish":
        finish(file_arg)
    elif option_arg == "grade":
        grade(file_arg)
    elif option_arg == "hint":
        hint(file_arg)